In [13]:
import pandas as pd

df = pd.read_csv("m4monthly_is_hallu_context36.csv")
df.head()

,item_id,group,uid,forecast_trend rule,forecast_frequency rule,forecast_pattern rule,forecast_ARMA rule,target_trend rule,target_frequency rule,target_pattern rule,...,forecast_trend rule.1,forecast_frequency rule.1,forecast_pattern rule.1,forecast_ARMA rule.1,forecast_hallu.1,target_trend rule.1,target_frequency rule.1,target_pattern rule.1,target_ARMA rule.1,targets_hallu.1
0,m4_M1,Monthly,M1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,True,True,False,True,False,True,True
1,m4_M10,Monthly,M10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,True,True,True,True,False,True,False
2,m4_M100,Monthly,M100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,True,True,False,True,False,True,True,False,True,False
3,m4_M1000,Monthly,M1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,True,False,True,True,False,True,False,True,True
4,m4_M10000,Monthly,M10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,True,True,False,True,False,True,True

In [8]:
print(df.shape)
df.columns

(47326, 23)

Index(['item_id', 'group', 'uid', 'forecast_trend rule',
       'forecast_frequency rule', 'forecast_pattern rule',
       'forecast_ARMA rule', 'target_trend rule', 'target_frequency rule',
       'target_pattern rule', 'target_ARMA rule', 'forecast_hallu',
       'targets_hallu', 'forecast_trend rule.1', 'forecast_frequency rule.1',
       'forecast_pattern rule.1', 'forecast_ARMA rule.1', 'forecast_hallu.1',
       'target_trend rule.1', 'target_frequency rule.1',
       'target_pattern rule.1', 'target_ARMA rule.1', 'targets_hallu.1'],
      dtype='object')

In [14]:
df["targets_hallu.1"].value_counts()

targets_hallu.1
True     26526
False    20800
Name: count, dtype: int64

In [16]:
df["forecast_hallu.1"].value_counts()

forecast_hallu.1
True     33805
False    13521
Name: count, dtype: int64

In [ ]:
# df = pd.read_csv("m4monthly_is_hallu.csv")
# df["targets_hallu"].value_counts()

Series([], Name: count, dtype: int64)

In [15]:
df["forecast_hallu"].value_counts()

Series([], Name: count, dtype: int64)

In [18]:
# intersection of ids classified as non-hallu

targets_non_hallu = df[df["targets_hallu.1"] == False]["item_id"]
forecast_non_hallu = df[df["forecast_hallu.1"] == False]["item_id"]

In [19]:
assert len(targets_non_hallu) == len(set(targets_non_hallu))
assert len(forecast_non_hallu) == len(set(forecast_non_hallu))

print(len(set(targets_non_hallu)), len(set(forecast_non_hallu)))
intersection = set(targets_non_hallu).intersection(set(forecast_non_hallu))
intersection.__len__() # the number of times both the target and the forecast were classified as non-hallucinating

20800 13521

8924

In [20]:
type3_targets_non_hallu = df[(df["target_ARMA rule.1"] == 1) & (df["target_pattern rule.1"] == 1)]["item_id"]
type3_forecasts_non_hallu = df[(df["forecast_ARMA rule.1"] == 1) & (df["forecast_pattern rule.1"] == 1)]["item_id"]

In [21]:
print(type3_targets_non_hallu.shape)
print(type3_forecasts_non_hallu.shape)

intersection = set(type3_targets_non_hallu).intersection(set(type3_forecasts_non_hallu))
intersection.__len__() # the number of times both the target and the forecast were classified as non-hallucinating

(6919,)
(6322,)

3869

In [46]:
for col in ["trend", "frequency", "pattern", "ARMA"]:
    print(df[f"target_{col} rule.1"].mean(), df[f"forecast_{col} rule.1"].mean())

0.4186916282804378 0.3740861260195242
0.9871318091535308 0.8721210328360732
0.2478341714913578 0.24840468241558553
1.0 1.0

In [49]:
df["target_trend rule.1"]

0        False
1         True
2         True
3        False
4        False
         ...
47321     True
47322    False
47323    False
47324    False
47325    False
Name: target_trend rule.1, Length: 47326, dtype: bool

In [1]:
import pandas as pd

df = pd.read_csv("outputs/chronos_m4_context.csv")

df.head()

,item_id,c1,c2,c3,c4,c5,c6,c7,c8,c9,...,c491,c492,c493,c494,c495,c496,c497,c498,c499,c500
0,m4_M1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6050.0,5640.0,6220.0,5740.0,6040.0,5130.0,5090.0,5210.0,4910.0,6890.0
1,m4_M10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7280.0,7140.0,7090.0,7010.0,6860.0,6820.0,6800.0,6730.0,6640.0,6630.0
2,m4_M100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2185.7,2171.5,2158.8,2156.5,2141.2,2132.0,2133.5,2135.4,2159.8,2167.0
3,m4_M1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1550.0,1880.0,1060.0,1460.0,900.0,880.0,800.0,1140.0,970.0,1430.0
4,m4_M10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2220.0,1980.0,2100.0,2220.0,2170.0,2470.0,2490.0,2680.0,2800.0,2780.0

In [36]:
ts_sizes = []
for id, row in df.iterrows():
    # print(row.isna().value_counts())
    false_count = row.notna().sum()
    ts_sizes.append(false_count)

In [39]:
ts_sizes = pd.Series(ts_sizes)
print(ts_sizes.mean(), ts_sizes.median(), ts_sizes.mode(), ts_sizes.std(), ts_sizes.var())

214.21315978531885 207.0 0    70
dtype: int64 120.12484223070881 14429.977720952684

In [1]:
import pandas as pd

df = pd.read_csv("outputs/chronos_m4monthly_gt_uids.csv")

df.head()

,item_id,group,uid,trend rule,frequency rule,pattern rule,ARMA rule,hallu
0,m4_M1,Monthly,M1,False,True,True,NaN,True
1,m4_M10,Monthly,M10,True,True,True,NaN,False
2,m4_M100,Monthly,M100,True,True,True,NaN,False
3,m4_M1000,Monthly,M1000,False,True,False,NaN,True
4,m4_M10000,Monthly,M10000,False,True,False,NaN,True

In [ ]:
df.hallu.value_counts().sum()

np.int64(47326)